# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/node-logtify-bugsnag
    docker:
      - image: circleci/node:8.9
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt-get update && sudo apt-get -y install gcc make
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-dependencies-{{ .Branch }}
          - v1-dependencies # fallback to using the latest cache if no exact match is found
      - run:
          name: Install dependencies
          command: make deps
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test project
          command: make test
      - persist_to_workspace:
          root: ~/node-logtify-bugsnag
          paths:
            - coverage
            - src

  sonarqube:
    docker:
        - image: circleci/openjdk:8-jdk-browsers
                 # Sonar need OpenJDK 8 to run correctly
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Install node
          command: |
            sudo apt install curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
            sudo apt install nodejs
      - run:
          name: Sonar analysis
          command: |
            cp -R /tmp/coverage /tmp/src /home/circleci/project
            make sonar
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sonarqube:
          requires:
            - build
